version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - yarn

  build:
    commands:
      - yarn build

artifacts:
  files:
    - .next/**/*
    - locales/**/*
    - static/**/*
    - package.json
    - next.config.js
    - tsconfig.json
    - tsconfig.server.json
    - .platform/**/*